# Generated by Django 3.0.8 on 2020-07-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Group', verbose_name='Сообщества'),
        ),
    ]
