# Generated by Django 3.0.8 on 2020-07-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200726_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='url',
            new_name='slug',
        ),
    ]
